name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kknode:$(date +%s)
    - name: Publish to docker repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
          name: kkmm/kknode:$(date +%s)
          repository: kkmm/kknode
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
