name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kktest:${{ github.ref_name	 }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to docker repository
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
          name: kkaoeu/kktest:${{ github.ref_name	 }}
          repository: kkaoeu/kktest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.5
      with: 
        host: 42.192.155.212
        username: ubuntu
        password: Km106822,
        script: |
          sudo docker pull kkaoeu/kktest:${{ github.ref_name	 }}
          sudo docker run -d -p 5656:5656 --name kktt kkaoeu/kktest:${{ github.ref_name	 }}
